# erp-academique-db/docker/docker-compose.dev.yml
version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-db-dev
    env_file:
      - ../config/dev.env
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ../scripts/init:/docker-entrypoint-initdb.d
    networks:
      - erp-network

volumes:
  db_data_dev:

networks:
  erp-network:
    driver: bridge